# Generated by Django 3.0.3 on 2021-01-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='Status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
