# Generated by Django 3.0.3 on 2021-01-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lendings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='status',
            new_name='Status',
        ),
    ]
